### ISSUE TITLE
Failed to load plugin venv... from 'pdm.utils'

### ISSUE THREAD

**Issue by robml** [pdm-project/pdm#1244]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Any `pdm` command I type that is the first message I get.

## Actual behavior

I got this message `Failed to load plugin venv=pdm_venv.plugin:entry_point: cannot import name 'is_venv_python' from 'pdm.utils'`

## Expected behavior

Namely I was trying to access `pdm list -g` and it would not bring it up.

## Environment Information

I was using PDM fine yesterday, no changes made to my system since then, only updated PDM hence why I suspect this may have been a bug.

**Comment by frostming** [comment]
No, see the index page of `pdm-venv`, it is deprecated and don't work on PDM 2.0, just uninstall it

**Comment by alexclarence** [comment]
As a closed issue this doesn't pop up in google search. Is it possible to keep it visible for people? I had the same problem and it wasn't immediately obvious to me that pdm-venv was deprecated when you upgrade pdm
