### ISSUE TITLE
Problems with pdm 1.5.1 when installed/upgraded via pipx

### ISSUE THREAD

**Issue by pohlt** [pdm-project/pdm#420]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

I was happily using pdm in various versions before 1.5.0 (even 1.5.0b's) which I installed/upgraded using pipx.
When I do an `pipx upgrade-all` which brings pdm to 1.5.1, I get an error message when tryping to install any package:

```
Error occurs
Traceback (most recent call last):
  File "c:\users\z001y9xs\.local\pipx\venvs\pdm\lib\site-packages\pdm\termui.py", line 189, in logging
    yield logger
  File "c:\users\z001y9xs\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\synchronizers.py", line 301, in synchronize
    with self.ui.logging("install"), self.environment.activate():
  File "c:\python37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "c:\users\z001y9xs\.local\pipx\venvs\pdm\lib\site-packages\pdm\models\environment.py", line 131, in activate
    bin_py = req_uninstall.bin_py
AttributeError: module 'pip._internal.req.req_uninstall' has no attribute 'bin_py'
```

A `pipx reinstall` did not help. The only mitigation was to remove pdm and install it without pipx.

## Environment Information

I had the same issue on both Windows and Python using both Python 3.7 and 3.8.

**Comment by frostming** [comment]
See #412 , the workaround is to downgrade the `pip` to `<21.1` inside the pipx managed venv.

The release with a fix will be out this week.

**Comment by linw1995** [comment]
Or you can install the HEAD of the master branch version to acquire this fix by executing these commands.

```
pipx uninstall pdm
pipx install "git+https://github.com/pdm-project/pdm.git@master#egg=pdm"
```

**Comment by pohlt** [comment]
Sorry for bothering you over a fixed issue. And thanks for the workarounds.

Works with pip 21.0 and breaks with pip 21.1 (ok, you are using internal stuff, but still): -1 for SemVer 😉

**Comment by andrewebdev** [comment]
I'm now getting similar error, but for setuptools.

```
Install setuptools 56.0.0 failed
Traceback (most recent call last):
  File "/home/andre/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/home/andre/.local/lib/python3.8/site-packages/pdm/core.py", line 184, in main
    return Core().main(args)
  File "/home/andre/.local/lib/python3.8/site-packages/pdm/core.py", line 145, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/home/andre/.local/lib/python3.8/site-packages/pdm/core.py", line 140, in main
    f(options.project, options)
  File "/home/andre/.local/lib/python3.8/site-packages/pdm/cli/commands/install.py", line 41, in handle
    actions.do_sync(
  File "/home/andre/.local/lib/python3.8/site-packages/pdm/cli/actions.py", line 128, in do_sync
    handler.synchronize()
  File "/home/andre/.local/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 305, in synchronize
    handlers[kind](key)
  File "/home/andre/.local/lib/python3.8/site-packages/pdm/installers/synchronizers.py", line 148, in install_candidate
    installer.install(can)
  File "/home/andre/.local/lib/python3.8/site-packages/pdm/installers/installers.py", line 47, in install
    self.install_wheel(candidate.wheel)
  File "/home/andre/.local/lib/python3.8/site-packages/pdm/installers/installers.py", line 53, in install_wheel
    enquoted_executable = distlib.scripts.enquote_executable(
AttributeError: module 'distlib.scripts' has no attribute 'enquote_executable'

```

**Comment by frostming** [comment]
@andrewebdev What version of `distlib` do you have? Try to upgrade it to the latest.

**Comment by andrewebdev** [comment]
tx didn't think of that. all working fine
